defaults: {}

branches:
  - match: local-deploy
    realms:
      - realm: 'local'
        proxy:
         - host: 'spec-python.totem.local'
           paths:
           - path: '/'
             port: 8080
        comptroller: {}
